server:
  port: 8001


ali:
  pay:
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmdaKbPZaSW//i8J7jwTIPeferuaYgaAOGFnsWQxMD2LZki3Ym1zDAAR03KHEVUw+IXSbIVxR6jI0MHgzLsbKIiSQbTRybf4W4pOWH/K3IhBBaxwM068/6m2WXPh5Nm5hIN79HhtlLr3JKnr+btoHS/P82u+rT9pMCQafvQ9vyeopd+yZxogc6ksGyMMcMkdRMF7I33z7XaWVDLHEAt/QgRiRPdRtt0vmPIyK8vmAqYoAYmsS136qk6OXtVJs4yhJOsUe9CqxABhCvwN6xVqvxNsX1iBqRBD2qg9s+4JgVfkMYNsXZGyqRSTTxgoXy4rXgje65O+5F0UaHMMcgpq/fwIDAQAB
    app-id: 2021000117671035
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do
    merchant-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCmNWD1K6AFNRrwbkgtd6L6tuqMDera95xbtl4c9cw6zQmNWZVjbnZtF2FBX4j9L4RXNrZPsZlRoyOcFW3CrzYTjpyCdF4oXJTH8ccEjIxR95XTtTY9fRXIyLoa82b/fC6KiH6+oqATm5Dt0wGo82szx1qinvZXQOzxwyUZJ2cFEyqpEgEiAjhpgeoXIgxF3PP8kdjAyU/APot/L5m+dZqaX0Te/RyJq/k2Dc/r8AP7MQ9y74ktv9Az4+2cCfdNSQQ9acftaQ/pJihSSp0yOt678k6HZmdT4Gd4tor20cCQW3BzjswPa3dywkf1KGI2b0q5c8vMr7YMDD6GZrzp1F07AgMBAAECggEAI3Wz79qU00eXLcB5ianCjbbEp4i4mGrHYxGvVoJiRhFEfnGkW4hPn8qjJy1Yrpuaoni7wJjlWvNxP3Wa6zQyV03Puk1VYUsPOvEsQp4xubMWtgotPkUXhrS8b8+KI+u8ijXAxK8xc7122CZybjcwoeVgQt2jNM5XPuUhXxJ2+i/YsuChKhe7oBsWX188yMFQwf1idq3jyE5Hsdz7KHCkCELonLkRoEG2a9RfbbYXBiU+yqCyDby3p3tonHm5PFUqQjv6tJjJEYwlj2NcIQAbQLfMHhiYrR+EvtDtQLU3FTCrzB+d0KDAIo8pvHEgvpXwWZ7l4v9RJS+C9z50354ZgQKBgQD+K8HZ+xjFJiEBYgwj8QD0b7dU3Pih+hLjrt2/iqEMYB9WfwOAGBl/h7ydLKaUM/FjHjW9YZm+SsS6TCqOoAGEKngLKMDqNUCKcgNOS3wlo4f2n1xizl+zGml/fXnJq2UGypwUzVdTqVi1KbA0ZFDJuNGlwNZqe47GNh7N47nv2wKBgQCnZ5Lxv727n9PFw9A4O7NcUU8saDihW1pq11/uiU00dYSTKjmTxwPoNDdusK9VHaB5sJxqYmFd0TDGjqF0pmye4ZQDbm33cowZzThXD4iiArfQFx4SCfLGDImvDjnUy43Gi+uc7MinswPEv+s2bm5aDGbV7Ul0fqUWo2ED5SD2IQKBgQCafMo0zfQ+UHCbQJcUeXYVHJoYEL9m5HL6xNyvgXll5j7l+gmMoBlPdJdmCS+uwOulTUVouJwUF6n/ejAbxJFnXdDdJ4YqVPfHrojn2+W3kvAfLLmgrMNqP1GEViXiODUNrbS0yCKeDT6HzrD1B0w7cAStdMpeqn8bZuXOSu5HJQKBgGGZaDmbwYGfKDe39zCh1etv2EoapVGl0ixSTzLiR+naziWCy7jVofiCYQMe7cohEMuB5V+85eltqhNJWuaIlPF4sPPjMSfAV+A/Hqbbfpx+Gy6uG7EGrc07yBYQpDTlTE5Ci2adQktLeln+TqMYdSv46Qe2ZUoPAC8Xp9s+fh4hAoGARawNGIfe43Rm54vqQtf0PYq55pWrimmuL9PbOfJQ+fIUSkBL/a61+/uJwvKzcZ7RcFRtD3wz4nSsnwwSJ/y0FwCD9O4dLqVCft8+mpBK519m//aQqUMRC/hXax3LV+/k4z6zH6Hh/9dN6HIeWUqDz6y5TUyjL8nK+CCYv5psen0=
    notify-url: http://xr36qu.natappfree.cc/notify
    return-url: http://localhost:8001/return
    sign-type: RSA2


spring:
  mvc:
    view:
      prefix: /
      suffix: .html